apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: backup-example
  labels:
    app: app2backup
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  - name: kanister-sidecar
    image: kanisterio/kanister-tools:0.20.0
    command: ["bash", "-c"]
    args:
    - "tail -f /dev/null"
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc2backup
