---
apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
    name: blue
    app: blue
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: blue
    image: percona
    args:
      - "--ignore-db-dir"
      - "lost+found"
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: k8sDem0
    ports:
      - containerPort: 3306
        name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: demo-vol1
  volumes:
  - name: demo-vol1
    persistentVolumeClaim:
      claimName: demo-vol1-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-cstor-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
