apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: BASE64_ENCODED_CA_CERTIFICATE
    server: https://api.containerized.me
  name: local
contexts:
- context:
    cluster: local
    namespace: secureapp
    user: user3445
  name: user3445-context
current-context: user3445-context
kind: Config
preferences: {}
users:
- name: user3445
  user:
    client-certificate: BASE64_ENCODED_CLIENT_CERTIFICATE
    client-key: BASE64_ENCODED_CLIENT_KEY
