apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-disk-1
spec:
  storageClassName: ""
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gce-disk-1
    fsType: ext4
